"""Rule test cases from roomkey tools/talk_identity.py at d0d52b9 (CASES, TYPE_CASES), verbatim."""

CASES = [  # text, speaker, message   (door side unless the text starts with "room:")
    ("Hi, hier ist Jonas, ich komme gleich runter.", "Jonas", "Ich komme gleich runter."),
    ("Hallo, ich bin's, Anna. Machst du auf?", "Anna", "Machst du auf?"),
    ("Anna hier, ich hab meinen Schlüssel vergessen.", "Anna", "Ich hab meinen Schlüssel vergessen."),
    ("Guten Tag, Paketdienst von DHL, ich habe ein Paket für Sie.", "Paketdienst · DHL", "Guten Tag, Paketdienst von DHL, ich habe ein Paket für Sie."),
    ("Hallo, hier ist die Polizei, bitte öffnen Sie die Tür.", "Polizei", "Bitte öffnen Sie die Tür."),
    ("Hallo, Paket für Schmidt.", "Paketdienst", "Hallo, Paket für Schmidt."),
    ("Amazon, ich stelle es vor die Tür.", "Paketdienst · Amazon", "Amazon, ich stelle es vor die Tür."),
    ("Hier ist Anna, Ihre Nachbarin. Haben Sie kurz Zeit?", "Anna · Nachbarin", "Ihre Nachbarin. Haben Sie kurz Zeit?"),
    ("Ich bin der Schornsteinfeger, ich muss kurz in den Keller.", "Schornsteinfeger", "Ich muss kurz in den Keller."),
    ("Mein Name ist Thomas Weber von den Stadtwerken, es geht um den Zähler.", "Thomas Weber · Stadtwerke", "Es geht um den Zähler."),
    ("Ich bin gleich da.", "", "Ich bin gleich da."),
    ("Ist Anna da?", "", "Ist Anna da?"),
    ("Ups, falsche Klingel, Entschuldigung.", "", "Ups, falsche Klingel, Entschuldigung."),
    ("Hi, it's Anna, can you open the door?", "Anna", "Can you open the door?"),
    ("Hallo, ich bin Ihr Nachbar von nebenan.", "Nachbar", ""),
    ("Hier ist die Feuerwehr!", "Feuerwehr", ""),
    ("Ich komme gleich runter.", "", "Ich komme gleich runter."),
    ("Guten Tag, Kowalski mein Name, ich komme wegen der Besichtigung.", "Kowalski", "Ich komme wegen der Besichtigung."),
    ("Soll ich es sonst beim Nachbarn abgeben?", "", "Soll ich es sonst beim Nachbarn abgeben?"),
    ("Hier ist Anna, soll ich die Polizei rufen?", "Anna", "Soll ich die Polizei rufen?"),
    ("Polizei, bitte öffnen Sie!", "Polizei", "Polizei, bitte öffnen Sie!"),
    ("Ich hab dir ein Taxi gerufen, es kommt in fünf Minuten.", "", "Ich hab dir ein Taxi gerufen, es kommt in fünf Minuten."),
    ("Hast du mein Paket von Amazon angenommen?", "", "Hast du mein Paket von Amazon angenommen?"),
    ("Hier ist Anna, hast du mein Paket von Amazon?", "Anna", "Hast du mein Paket von Amazon?"),
    ("Hallo, Paket von Hermes für Schmidt.", "Paketdienst · Hermes", "Hallo, Paket von Hermes für Schmidt."),
    ("Guten Tag, hier ist DHL.", "Paketdienst · DHL", ""),
    ("Ich habe Ihre Katze gefunden, die saß bei uns im Garten.", "", "Ich habe Ihre Katze gefunden, die saß bei uns im Garten."),
    ("Hallo, Paket. DHL.", "Paketdienst · DHL", "Hallo, Paket. DHL."),
    ("Gerichtsvollzieher Braun, ich muss Ihnen etwas zustellen.", "Braun · Gerichtsvollzieher", "Gerichtsvollzieher Braun, ich muss Ihnen etwas zustellen."),
    ("Moin, der Hausmeister. Ich muss mal an die Heizung.", "Hausmeister", "Moin, der Hausmeister. Ich muss mal an die Heizung."),
    ("Das Paket von Amazon ist leider beschädigt angekommen.", "", "Das Paket von Amazon ist leider beschädigt angekommen."),
    ("Hallo, isch habe Paket für Nachbar. Sie nehmen?", "Paketdienst", "Hallo, isch habe Paket für Nachbar. Sie nehmen?"),
    ("Die Handwerker sind da, wo sollen wir anfangen?", "Handwerker", "Die Handwerker sind da, wo sollen wir anfangen?"),
    ("Ich habe ein Paket für dich angenommen.", "", "Ich habe ein Paket für dich angenommen."),
    ("Ihr Nachbar, Klaus. Kann ich mir kurz die Leiter ausleihen?", "Klaus · Nachbar", "Ihr Nachbar, Klaus. Kann ich mir kurz die Leiter ausleihen?"),
    ("Hier ist Frau Weber von nebenan, ich habe Ihre Post.", "Frau Weber · Nachbar", "Ich habe Ihre Post."),
    ("Hier sind Anna und Jonas, wir wollten euch abholen.", "Anna und Jonas", "Wir wollten euch abholen."),
    ("Hallo, ich bin Zoë, die neue Babysitterin.", "Zoë", "Die neue Babysitterin."),
    ("Mein Name ist Nguyễn Văn Minh, ich wohne im dritten Stock.", "Nguyễn Văn Minh", "Ich wohne im dritten Stock."),
    ("Hier ist, äh, der Jonas.", "Jonas", ""),
    ("Ich bin Vegetarier, bring bitte nichts mit Fleisch mit.", "", "Ich bin Vegetarier, bring bitte nichts mit Fleisch mit."),
    ("Hier ist Wasser im Keller!", "", "Hier ist Wasser im Keller!"),
    ("Wohnt hier Herr Özdemir?", "", "Wohnt hier Herr Özdemir?"),
    ("Guten Tag, ich komme von der Telekom wegen dem Glasfaseranschluss.", "Telekom", "Wegen dem Glasfaseranschluss."),
    ("Mein Name ist Weber, ich bin Gerichtsvollzieherin.", "Weber · Gerichtsvollzieherin", "Ich bin Gerichtsvollzieherin."),
    ("Servus, i bin da Sepp, is da Jonas dahoam?", "Sepp", "Is da Jonas dahoam?"),
    ("Hilfe, hier ist die Polizei! Untertitel im Auftrag des ZDF, 2021.", "Polizei", "Hilfe!"),
    ("room:Lieferando ist da, kannst du runtergehen?", "", "Lieferando ist da, kannst du runtergehen?"),
    ("room:Wagner, hallo?", "Wagner", ""),
    ("room:Hier ist Papa, stell es vor die Tür.", "Papa", "Stell es vor die Tür."),
    ("Ich bin's, Schatz, machst du auf?", "", "Ich bin's, Schatz, machst du auf?"),
    ("Hallo, das hier ist Anna, und ich bin Paul, wir wollen zu Jonas.", "Paul", "Das hier ist Anna, und wir wollen zu Jonas."),
    ("Guten Tag, ich bin von der Deutschen Glasfaser, wir bauen hier gerade aus.", "Deutschen Glasfaser", "Wir bauen hier gerade aus."),
    ("Hallo, Ihre Nachbarin hier, die Frau Schmitz, Sie haben das Licht am Auto angelassen.", "Frau Schmitz · Nachbarin", "Sie haben das Licht am Auto angelassen."),
    ("Guten Tag, ich bin vom Wasserwerk, bei Ihnen ist ein Rohrbruch.", "Wasserwerk", "Bei Ihnen ist ein Rohrbruch."),
    ("Servus, der Huber Franz, ich hätte ein Paket für euch.", "Huber Franz", "Ich hätte ein Paket für euch."),
    ("Hallo, von Bülow hier, wir hatten telefoniert.", "von Bülow", "Wir hatten telefoniert."),
    ("Huhu, die Omi ist da!", "Omi", "Omi ist da!"),
    ("room:Ich bin Oma besuchen, bin um sechs zurück.", "", "Ich bin Oma besuchen, bin um sechs zurück."),
    ("Guten Tag, Physiotherapie Hausbesuch, ich bin Tim.", "Tim · Physiotherapie", "Physiotherapie Hausbesuch."),
    ("Hier, delivery for Schmidt.", "Paketdienst", "Hier, delivery for Schmidt."),
    ("Hallo, ich bin der neue Vermieter, Herr Schäfer, ich wollte mich kurz vorstellen.", "Herr Schäfer · Vermieter", "Ich wollte mich kurz vorstellen."),
    ("Hallo, DPD, äh, nee, Quatsch, GLS. Paket für Sie.", "Paketdienst · GLS", "Hallo, GLS. Paket für Sie."),
    ("Hier ist Mar... äh, Marion. Entschuldigung, ich bin total erkältet.", "Marion", "Entschuldigung, ich bin total erkältet."),
    ("Amazon-Lieferung, ich lege es vor die Tür, okay?", "Paketdienst · Amazon", "Amazon-Lieferung, ich lege es vor die Tür, okay?"),
    ("Guten Tag, wir sind vom Deutschen Roten Kreuz und sammeln Spenden.", "Deutschen Roten Kreuz", "Und sammeln Spenden."),
    ("Jen dobry, guten Tag, ich bin Paketbote, Hermes, bitte aufmachen.", "Paketdienst · Hermes", "Jen dobry, guten Tag, bitte aufmachen."),
    ("Hier sind Yusuf und, äh, Can. Wir holen die Umzugskartons ab.", "Yusuf und Can", "Wir holen die Umzugskartons ab."),
    ("Hallo, also meine Frau hat gesagt, dass der Herr Dr. Lang hier irgendwo wohnen soll.", "", "Hallo, also meine Frau hat gesagt, dass der Herr Dr. Lang hier irgendwo wohnen soll."),
    ("Die Tanja.", "Tanja", ""),
    ("room:Ich bin der Meinung, dass Sie hier falsch sind.", "", "Ich bin der Meinung, dass Sie hier falsch sind."),
    ("Wohnt hier ein Herr Schulz? Ich hab einen Brief für ihn, der lag bei mir.", "", "Wohnt hier ein Herr Schulz? Ich hab einen Brief für ihn, der lag bei mir."),
    ("Tom ist mein Name.", "Tom", ""),
    ("Hier ist mein Pass.", "", "Hier ist mein Pass."),
    ("Hier ist dein Papa!", "Papa", ""),
    ("Ich bin Kanadier.", "", "Ich bin Kanadier."),
    ("Ich bin der Nächste.", "", "Ich bin der Nächste."),
    ("Raus hier, oder ich rufe die Polizei!", "", "Raus hier, oder ich rufe die Polizei!"),
]


TYPE_CASES = [  # text, side, vtype, urgent
    ("Guten Tag, Paketdienst von DHL, ich habe ein Paket für Sie.", "door", "parcel", False),
    ("Hallo, die Apotheke, ich bringe Ihre Medikamente.", "door", "pharmacy", False),
    ("Blumen für Frau Schmidt!", "door", "flowers", False),
    ("Hallo, Flink, Ihre Einkäufe.", "door", "shopping", False),
    ("Guten Tag, wir sammeln Spenden für das Tierheim.", "door", "sales", False),
    ("Guten Tag, wir sind von den Zeugen Jehovas.", "door", "religion", False),
    ("Süßes oder Saures!", "door", "seasonal", False),
    ("Wir sind die Sternsinger und bringen den Segen.", "door", "seasonal", False),
    ("Guten Tag, ich bin Kandidat für den Stadtrat und wollte mich vorstellen.", "door", "campaign", False),
    ("Hallo, ich bin ein Freund von Jonas, darf er raus zum Spielen?", "door", "kids_friend", False),
    ("Ich bin's, Oma!", "door", "family", False),
    ("Hallo, ich bin Susanne Maier.", "door", "name", False),
    ("Hallo, hier ist die Polizei.", "door", "police", False),
    ("Hilfe! Mein Mann ist gestürzt, bitte rufen Sie einen Krankenwagen!", "door", "emergency", True),
    ("Hier ist Anna von nebenan, bitte helfen Sie mir, es brennt!", "door", "neighbour", True),
    ("Kann ich Ihnen helfen?", "door", "", False),
    ("Soll ich die Polizei rufen?", "door", "", False),
    ("Danke für die Hilfe gestern.", "door", "", False),
    ("Hier ist Papa, ich komme gleich.", "room", "name", False),
]
